### ISSUE TITLE
Docker Image for cluster-smi

### ISSUE THREAD

**Issue by ieggel** [PatWie/cluster-smi#13]
Hi @PatWie ,

I quickly created a Dockerfile in order to build a Docker Image out of cluster-smi.
Have a look here:
https://github.com/ieggel/cluster-smi-docker

It's quite nice in the sense that it automates the cumbersome cluster-smi build process in a reproducible way. Once the Docker Image build it should be able to run anywhere.

If you think it is useful you can link to the repo. I'm also open for suggestions. I created the readme quite quickly, so there might still be some typos/other mistakes. I will review it again next week.

Cheers,
-Ivan

**Comment by PatWie** [comment]
I also thought about using docker. And I like docker-compose setups. But this is the beautify of Go. It is a simple portable binary. The only missing part is static linkage to libzmq.

Maybe
https://github.com/pebbe/zmq4/issues/121
is worth a try.

**Comment by ieggel** [comment]
Having it on Docker brings several advantages:
- no installation of libraries or other tools
- no compilation
- no OS requirements
- no version hell
- reproducability
- adding a new node to a gpu cluster takes second
- setting up a cluster of 10 nodes takes around 1 minute once the image is
built
- does not pollute system
- ...

It was just a proposition for people that prefer to run it on Docker, not
pro/cons of Docker or Go.

PS: nice tool. Works great!

Cheers,
-Ivan

**Comment by PatWie** [comment]
I had a look at your Dockerfile. I suggest to use the `CLUSTER_SMI_CONFIG_PATH` env-var and add the [YAML config file](https://github.com/PatWie/cluster-smi/blob/master/cluster-smi.example.yml) via a volume. So it can be re-used at different setups (different ips, ports, etc) without building the entire container from scratch.

From my understanding, https://github.com/ieggel/cluster-smi-docker/blob/master/Dockerfile#L34 this dynamic linkage does not work in general, when the path changes. Can you run the produced binary at a different machine?

I will consider this dockerfile for CI-testing though.

**Comment by ieggel** [comment]
Hi Pat,

Regarding the config,that's definitely better than the current solution. I
will have a look as soon as i can.

Regarding PKG_CONFIG_PATH: It will work on any machine, since everything
needed is directly included in the Docker image. You say it does not work
if the  path changes. OK this is true, but in a Docker image the path will
never change, since a docker image can be seen as a self-containing
(EVERYTHING needed is included in the image) read-only layer. So no matter
where the docker build is run, it will always produce the same image. Also,
running the Docker container (instance of a Docker image) will work on any
machine where docker is installed (additionally docker-nvidia needed for
gpu related stuff).

Cheers,
-Ivan

**Comment by ieggel** [comment]
Hi @PatWie 
Updated the repo in order to support the provision of the YAML config file. 
Have a look here: https://github.com/ieggel/cluster-smi-docker
