### ISSUE TITLE
Possible deadlock?

### ISSUE THREAD

**Issue by minostauros** [PatWie/cluster-smi#18]
Currently using cluster-smi 24/7, but cluster-smi seems stuck (./cluster-smi stops working, no output at all) once or twice a day.
Not exactly sure where the problem comes from, so I'm just rebooting the router+client computer when it stops working.

Any ideas?

**Comment by PatWie** [comment]
Here, it is running for nearly one entire year 24/7 without any issues. Make sure your firewall has the correct settings and the ports are not blocked (my best guess: iptables has a kind of rules where after some time traffic is blocked).

**Comment by minostauros** [comment]
Great, I'll report back after looking into network sides. Might take some days.

**Comment by minostauros** [comment]
Doesn't seem to be a network-side problem since there is no firewall/iptables rule defined in my cluster (currently using about 18 GPU servers and 54 GPUS), but found the one that freezes is router but not client.
I'll close this issue if no further steps can be made next week.

**Comment by PatWie** [comment]
The mutex and copy action in these lines

https://github.com/PatWie/cluster-smi/blob/692a377f4eaa5303a263337b5b0a6de96b4d5b78/cluster-smi-router.go#L86-L92

probably do not scale that well. The measly maximum number of nodes I used has been 8. These lines have always been a thorn in my side. But unfortunately they worked, so I never had the motivation to change them.

Could you please try it with less nodes just to verify for that it indeed works for less than 10 machines?

**Comment by minostauros** [comment]
> Could you please try it with less nodes just to verify for that it indeed works for less than 10 machines?

Tried with 9 machines, but no luck. It still needs to be restarted.

**Comment by minostauros** [comment]
Closing this issue since it's very hard for me to find the source of problem (don't really have time to look into details while the servers are up online and being used by others).
My current workaround is to restart cluster-smi-router 4 times every day using crontab.
