### ISSUE TITLE
Multiple GPU cluster within same network

### ISSUE THREAD

**Issue by nilesh-patil-automatonai** [PatWie/cluster-smi#21]
What are the steps for cluster setup on ubuntu ? 
Is there any Master and Slave structure in it ?

**Comment by PatWie** [comment]
Hi,

you simply start the `cluster-smi-router` at a specific host. Each node (`cluster-smi-node`) is started on each computation node. There is no hierarchy all nodes will talk to the same `cluster-smi-router`.

The `cluster-smi-router` will give a feedback if a  `cluster-smi-node` has successfully connected to the `cluster-smi-router`.

And then, each client can simply query the current stats via calling `cluster-smi`.

**Comment by nilesh-patil-automatonai** [comment]
Thanks. 
But is there any proper documentation regarding it ?.
Because I want the output as follows :-

GPU       Name              Memory usage
Fan         Temp

0          TitanRTX
10%        45C                   1816MB / 24000MiB

1          TitanRTX
20%        35C                   16MB / 24000MiB

2          TitanRTX
10%        30C                   186MB / 24000MiB

**Comment by PatWie** [comment]
The documentation is really as I wrote:

* copy `cluster-smi-router` to a dedicated machine and start
* copy `cluster-smi-node` to your node
  * point `CLUSTER_SMI_CONFIG_PATH` on that node to the configfile, e.g. `export CLUSTER_SMI_CONFIG_PATH=/path/to/config.yml`
  * start `cluster-smi-node` 
* copy `cluster-smi` to any of your machine, eg. laptop
  * point `CLUSTER_SMI_CONFIG_PATH` on that node to the configfile, e.g. `export CLUSTER_SMI_CONFIG_PATH=/path/to/config.yml`
  * start `cluster-smi`

**Comment by nilesh-patil-automatonai** [comment]
Thank you Sir.
I will try above instructions and let you know the result.
