### ISSUE TITLE
cluster-smi make errors

### ISSUE THREAD

**Issue by junaidmsme** [PatWie/cluster-smi#25]
Hi, I am new to go program compilation. We are trying to follow the steps of installation, and we have previously installed zmq 4.1.8 and cuda 12.4 as module in Ubuntu 22.04 HPC Cluster. We have loaded the modules below and edited the config.go to match c.RouterIp to our server IP and edited nvml.go to set CFLAGS,LDFLAGS to the cuda 12.4 paths.

 module list
Currently Loaded Modulefiles:
 1) libs/zmq/4.1.8   2) cuda/12.4

Please let me know if there is any other prerequisite apart from above. I tried to compile and encountering below issues, kindly suggest how to proceed. Apologies if this is fairly simple and I ended up making it complicated :) .

/export/apps/cluster-smi# make all
cd proc; go install
# github.com/patwie/cluster-smi/proc
proc.c: In function ‘read_pid_info’:
proc.c:172:31: warning: use of assignment suppression and length modifier together in gnu_scanf format [-Wformat=]
  172 |     bool success = fscanf(fp, "%*d (%s %*c %*d %*d %*d %*d %*d %*u %*lu %*lu %*lu %*lu %lu %lu %*ld %*ld %*d %*d %*d %*d %llu",
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
proc.c:172:31: warning: use of assignment suppression and length modifier together in gnu_scanf format [-Wformat=]
proc.c:172:31: warning: use of assignment suppression and length modifier together in gnu_scanf format [-Wformat=]
proc.c:172:31: warning: use of assignment suppression and length modifier together in gnu_scanf format [-Wformat=]
proc.c:172:31: warning: use of assignment suppression and length modifier together in gnu_scanf format [-Wformat=]
proc.c:172:31: warning: use of assignment suppression and length modifier together in gnu_scanf format [-Wformat=]
proc.c: In function ‘get_mem’:
proc.c:50:3: warning: ignoring return value of ‘fgets’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   50 |   fgets(line, 100, statusf);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~
proc.c:52:3: warning: ignoring return value of ‘fgets’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   52 |   fgets(line, 100, statusf);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~
proc.c:54:3: warning: ignoring return value of ‘fgets’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   54 |   fgets(line, 100, statusf);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~
go build cluster-smi.go config.go
cluster/data.go:5:2: github.com/mattn/go-runewidth@v0.0.3-0.20170510074858-97311d9f7767: missing go.sum entry; to add it:
        go mod download github.com/mattn/go-runewidth
cluster-smi.go:7:2: missing go.sum entry for module providing package github.com/pebbe/zmq4; to add:
        go mod download github.com/pebbe/zmq4
cluster-smi.go:8:2: missing go.sum entry for module providing package github.com/vmihailenco/msgpack; to add:
        go mod download github.com/vmihailenco/msgpack
config.go:4:2: missing go.sum entry for module providing package gopkg.in/yaml.v2; to add:
        go mod download gopkg.in/yaml.v2
make: *** [Makefile:6: all] Error 1

**Comment by junaidmsme** [comment]
I was able to go ahead the error by following the go mod download messages, now encountering a different issues.

/export/apps/cluster-smi# make all
cd proc; go install
# github.com/patwie/cluster-smi/proc
proc.c: In function ‘read_pid_info’:
proc.c:172:31: warning: use of assignment suppression and length modifier together in gnu_scanf format [-Wformat=]
  172 |     bool success = fscanf(fp, "%*d (%s %*c %*d %*d %*d %*d %*d %*u %*lu %*lu %*lu %*lu %lu %lu %*ld %*ld %*d %*d %*d %*d %llu",
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
proc.c:172:31: warning: use of assignment suppression and length modifier together in gnu_scanf format [-Wformat=]
proc.c:172:31: warning: use of assignment suppression and length modifier together in gnu_scanf format [-Wformat=]
proc.c:172:31: warning: use of assignment suppression and length modifier together in gnu_scanf format [-Wformat=]
proc.c:172:31: warning: use of assignment suppression and length modifier together in gnu_scanf format [-Wformat=]
proc.c:172:31: warning: use of assignment suppression and length modifier together in gnu_scanf format [-Wformat=]
proc.c: In function ‘get_mem’:
proc.c:50:3: warning: ignoring return value of ‘fgets’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   50 |   fgets(line, 100, statusf);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~
proc.c:52:3: warning: ignoring return value of ‘fgets’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   52 |   fgets(line, 100, statusf);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~
proc.c:54:3: warning: ignoring return value of ‘fgets’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   54 |   fgets(line, 100, statusf);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~
go build cluster-smi.go config.go
go build cluster-smi-router.go config.go
go build cluster-smi-node.go config.go cluster.go
package command-line-arguments
        imports github.com/patwie/cluster-smi/nvml: C source files not allowed when not using cgo or SWIG: bridge.c
make: *** [Makefile:8: all] Error 1
root@:/export/apps/cluster-smi#

**Comment by PatWie** [comment]
There is a docker file
https://github.com/PatWie/cluster-smi/blob/master/.drone/Dockerfile
and build-steps
https://github.com/PatWie/cluster-smi/blob/master/.drone.yml
