### ISSUE TITLE
Show processes running on the GPUs

### ISSUE THREAD

**Issue by PatWie** [PatWie/cluster-smi#5]
Nvidia-smi provides information which processes are running on the GPUs. However this would cause a long list when showing these information for all nodes at the same time. Not sure how to display these information.

Information are stored in the `nvmlProcessInfo_t` structure which can be obtained via `nvmlReturn_t nvmlDeviceGetComputeRunningProcesses ( nvmlDevice_t device, unsigned int* infoCount, nvmlProcessInfo_t* infos )`. Further this only returns the pid and used memory. Querying the command requires to parse `/proc/pid/stat` like in [cluster-top](https://github.com/PatWie/cluster-top) which is OS dependent.

**Comment by thangvubk** [comment]
Is the objective of this app for Machine Learning/Deep Learning users? In my case, it is only one or two processes per node. 

![image](https://user-images.githubusercontent.com/20570053/34914324-bec399b2-f953-11e7-88d5-4239bb135924.png)

The below is my opinion to show the processes (save the char as much as possible):
- Remove Mem-util column, it has the same information with Memory-Usage
- Remove one 'MiB' in Mem-usage
- Set max-char for all column (avoid unbalanced table due to too long name)
- There might be some processes with minimal GPU usage, in those cases, you can set the minimum GPU usage for display. 

```
+---------+-------------------+----------------+------------------+--------+
| Node    | Gpu               | Process        | Memory-Usage     | G-Util |
+---------+-------------------+----------------+------------------+--------+
| node-00 | 0: TITAN Xp       | python 3850MiB |  3857 / 12189MiB | 0%     |
|         | 1: TITAN Xp       | python 7200MiB | 11689 / 12189MiB | 0%     | 
|         |                   | caffe  3450MiB |                  |        |
|         | 2: TITAN Xp       |                | 10787 / 12189MiB | 0%     |
|         | 3: TITAN Xp       |                | 10965 / 12189MiB | 100%   |
+---------+-------------------+----------------+------------------+--------+
| node-01 | 0: TITAN Xp       |                | 11667 / 12189MiB | 100%   |
|         | 1: TITAN Xp       |                | 11667 / 12189MiB | 96%    |
|         | 2: TITAN Xp       |                |  8497 / 12189MiB | 100%   |
|         | 3: TITAN Xp       |                |  8499 / 12189MiB | 98%    |
+---------+-------------------+----------------+------------------+--------+
| node-03 | 0: GeForce GTX... |                |  1447 / 11172MiB | 8%     |
|         | 1: GeForce GTX... |                |  1453 / 11172MiB | 99%    |
|         | 2: GeForce GTX... |                |  1673 / 11172MiB | 0%     |
|         | 3: GeForce GTX... |                |  6812 / 11172MiB | 36%    |
+---------+-------------------+----------------+------------------+--------+
```
Edited: you can remove ':' between 0: TITANXp

**Comment by thangvubk** [comment]
In addition, it is better if you add current date time on the table (as in nvidia-smi). Sometimes the table doesn't move and doesn't change any values. It looks like the app doesn't update, although it is updated every 1s.

**Comment by PatWie** [comment]
This is now possible with `cluster-smi -p`. Resolving PID -> name will be done after I cleaned up the `cluster-top` implementation, and merge both projects as they can share some parts.

**Comment by thangvubk** [comment]
Thank you! Keep up the good work :)

**Comment by PatWie** [comment]
Done. See README.

**Comment by thangvubk** [comment]
It is very nice now. :) ah. I think it need to have -n option. Which show information in the specified node(s). Example -n node1 node2. It will be helpful with the server having many nodes.

**Comment by PatWie** [comment]
This is an easy one. Feel free to submit a PR. I don't need this option and will not implement it.

**Comment by thangvubk** [comment]
:D thank you

*Vu Van Thang*
Ha Noi university of science and technology
Phone numbers: 01648538155


2018-01-19 15:15 GMT+09:00 Patrick Wieschollek <notifications@github.com>:
